DROP DATABASE IF EXISTS role_DB;

CREATE DATABASE role_DB;

USE role_DB;
CREATE TABLE roles(
  id INT NOT NULL AUTO_INCREMENT,
  title VARCHAR(30) NOT NULL,
  salary DECIMAL NOT NULL,
  department_id INT REFERENCES department(id),
  PRIMARY KEY (id)
);